/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public Connection connection;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNamelg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordlg = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        toRegisterPage = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        forgotpass = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 730, 740));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("User Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, -1));

        userNamelg.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(userNamelg, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, 217, 41));
        userNamelg.getAccessibleContext().setAccessibleName("userName");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        passwordlg.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        getContentPane().add(passwordlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 217, 41));
        passwordlg.getAccessibleContext().setAccessibleName("password");

        loginbtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        loginbtn.setText("Log In");
        loginbtn.setActionCommand("loginbutton");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 550, 70, 45));

        toRegisterPage.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        toRegisterPage.setText("New Here? Click Here to Register.");
        toRegisterPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toRegisterPageMouseClicked(evt);
            }
        });
        getContentPane().add(toRegisterPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 630, -1, -1));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 153, 153));
        label1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        label1.setText("HOSTEL MANAGEMENT SYSTEM");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 110));

        forgotpass.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        forgotpass.setText("Forgot Password?");
        forgotpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpassMouseClicked(evt);
            }
        });
        getContentPane().add(forgotpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, -1, -1));

        btnexit.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 550, 70, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        if(passwordlg.getText().equals("") || userNamelg.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Some fields are empty!!");
        }else {
        try {
            
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sn;password=872524;" + "databaseName=ProjectHostelManagementSystem;";
             connection = DriverManager.getConnection(connectionUrl);
             java.sql.Statement stmt = connection.createStatement();

            String userName= userNamelg.getText();
            String password= passwordlg.getText();
            
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM Login_User WHERE UserName = '"+userName+"' and Password = '"+password+"'");
            
            
            if (resultSet.next()) {
                
                dispose();
                HomePage m=new HomePage();
                m.show();
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "User Name or Password wrong!!");
                userNamelg.setText("");
                passwordlg.setText("");
            }
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void toRegisterPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toRegisterPageMouseClicked
        // TODO add your handling code here:
        
        dispose();
        Register reg= new Register();
        reg.show();
    }//GEN-LAST:event_toRegisterPageMouseClicked

    private void forgotpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassMouseClicked
        // TODO add your handling code here:
        
        setVisible(false);
        new forgotpassword().setVisible(true);
    }//GEN-LAST:event_forgotpassMouseClicked

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel forgotpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordlg;
    private javax.swing.JLabel toRegisterPage;
    private javax.swing.JTextField userNamelg;
    // End of variables declaration//GEN-END:variables
}
