/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    public void validPassword()
    {
        String pass = regPass.getText();
        String pass2 = reTypePass.getText();
        
        if(!pass.equals(pass2))
        {
            JOptionPane.showMessageDialog(this, "The Password does not match, please check again!");
        }
    }
    
    public boolean verifyFields()
    {
        String FULLNAME = regName.getText();
        String USERNAME =regUserName.getText();
        String EMAIL = regMail.getText();
        String NUMBER = regnumber.getText();
        String PASSWORD = String.valueOf(regPass.getPassword());        
        String CONFIRMPASS = String.valueOf(reTypePass.getPassword());
        
        
        if (FULLNAME.trim().equals("") || USERNAME.trim().equals("") || EMAIL.trim().equals("") || NUMBER.trim().equals("") || PASSWORD.trim().equals("") || CONFIRMPASS.trim().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);              
            return false;
        }
        else{
            return true;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regName = new javax.swing.JTextField();
        regUserName = new javax.swing.JTextField();
        regMail = new javax.swing.JTextField();
        regPass = new javax.swing.JPasswordField();
        reTypePass = new javax.swing.JPasswordField();
        RegisterToLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        regnumber = new javax.swing.JTextField();
        jButnclose = new javax.swing.JButton();
        jBtnreset = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Full Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("User Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Email ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Re Type Password :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        regName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(regName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 250, 41));

        regUserName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(regUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 250, 41));

        regMail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        regMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMailActionPerformed(evt);
            }
        });
        getContentPane().add(regMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 250, 41));

        regPass.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 250, 41));

        reTypePass.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(reTypePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 250, 41));

        RegisterToLogin.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        RegisterToLogin.setText("Register");
        RegisterToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, -1, 40));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        regnumber.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(regnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 250, 41));

        jButnclose.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButnclose.setText("Back");
        jButnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButncloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, -1, 40));

        jBtnreset.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jBtnreset.setText("Reset");
        jBtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnresetActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, -1, 40));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(153, 153, 255));
        label1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        label1.setText("REGISTRATION");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reg.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 460, 630));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 590, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public Connection connection;
     
    private void regMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regMailActionPerformed

    private void RegisterToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterToLoginActionPerformed
        // TODO add your handling code here:

        validPassword();
        verifyFields();
                
                
        String fullName=regName.getText();
        String userName=regUserName.getText();
        String email=regMail.getText();
        String phonenumber = regnumber.getText();
        String password=regPass.getText();
        String confirmPass=reTypePass.getText();
        
        boolean mailFormat = Pattern.matches("[^.\\s][a-z0-9\\.\\_]{3,64}@([a-z]){2,50}.[a-z]{2,}", email);
        boolean phoneFormat = Pattern.matches("[0-9]{11,}", phonenumber);
        boolean userName1 = true;
        boolean Name1 = true;
        
  
        for (int i=0; i<userName.length(); i++) {

            if ((userName.charAt(i) >= '0' && userName.charAt(i) <= '9')) {

                userName1=false;

                JOptionPane.showMessageDialog(null, "User name Invalid");

                return;
            }
        }
        for (int i=0; i<fullName.length(); i++) {

            if ((fullName.charAt(i) >= '0' && fullName.charAt(i) <= '9')) {

                Name1=false;

                JOptionPane.showMessageDialog(null, "Name is Invalid");

                return;
            }
        }       
        
        try{
            
            if(mailFormat && phoneFormat){
                
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sn;password=872524;" + "databaseName=ProjectHostelManagementSystem;";
             connection = DriverManager.getConnection(connectionUrl);
             
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Login_User VALUES ('"+fullName+"','"+userName+"','"+email+"', '"+phonenumber+"', '"+password+"','"+confirmPass+"')";
                //dbconnect q=new dbconnect();
                //q.connecttodb();
                //q.insertDataToDB(sql);
                //q. disconnectFromDB();
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Registration Complete.");   
                dispose();
                login home= new login();
                home.show();
            
            }else if(!mailFormat) 
                    {
                JOptionPane.showMessageDialog(null, "Email format invalid");
                
            } else if (!phoneFormat) {
                JOptionPane.showMessageDialog(null, "Phone format invalid");
            }
              
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RegisterToLoginActionPerformed

    private void jBtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnresetActionPerformed
        // TODO add your handling code here:
        
        regName.setText("");
        regUserName.setText("");
        regMail.setText("");
        regnumber.setText("");
        regPass.setText("");
        reTypePass.setText("");
        
    }//GEN-LAST:event_jBtnresetActionPerformed

    private void jButncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButncloseActionPerformed
        // TODO add your handling code here:
        
        dispose();
        login home= new login();
        home.show();
    }//GEN-LAST:event_jButncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterToLogin;
    private javax.swing.JButton jBtnreset;
    private javax.swing.JButton jButnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JPasswordField reTypePass;
    private javax.swing.JTextField regMail;
    private javax.swing.JTextField regName;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JTextField regUserName;
    private javax.swing.JTextField regnumber;
    // End of variables declaration//GEN-END:variables
}
